-- V36: Replace the vehicle_features catalog with the canonical feature list.
-- NOTE: this deletes all existing vehicle_features rows first. Because
-- inventory_vehicle_features.feature_id has ON DELETE CASCADE back to
-- vehicle_features(id) (see V33), any inventory-to-feature associations
-- created against the old rows are removed along with them.

DELETE FROM vehicle_features;

INSERT INTO vehicle_features (name, slug, image, status, created_at, updated_at) VALUES
    ('Back camera', 'back-camera', NULL, 1, NOW(), NOW()),
    ('Automatic emergency braking', 'automatic-emergency-braking', NULL, 1, NOW(), NOW()),
    ('Adaptive Highlights', 'adaptive-highlights', NULL, 1, NOW(), NOW()),
    ('Bicycle Detection', 'bicycle-detection', NULL, 1, NOW(), NOW()),
    ('Brake Assist', 'brake-assist', NULL, 1, NOW(), NOW()),
    ('Forward Collision Warning', 'forward-collision-warning', NULL, 1, NOW(), NOW()),
    ('Left turn crash avoidance', 'left-turn-crash-avoidance', NULL, 1, NOW(), NOW()),
    ('Obstacle detection', 'obstacle-detection', NULL, 1, NOW(), NOW()),
    ('Pedestrian detection', 'pedestrian-detection', NULL, 1, NOW(), NOW()),
    ('Curve speed warning', 'curve-speed-warning', NULL, 1, NOW(), NOW()),
    ('High speed alert', 'high-speed-alert', NULL, 1, NOW(), NOW()),
    ('Adaptive cruise control', 'adaptive-cruise-control', NULL, 1, NOW(), NOW()),
    ('Adaptive Headlights', 'adaptive-headlights', NULL, 1, NOW(), NOW()),
    ('Electronic stability control', 'electronic-stability-control', NULL, 1, NOW(), NOW()),
    ('Traction control', 'traction-control', NULL, 1, NOW(), NOW()),
    ('Tire pressure monitoring system', 'tire-pressure-monitoring-system', NULL, 1, NOW(), NOW()),
    ('Temperature Warning', 'temperature-warning', NULL, 1, NOW(), NOW()),
    ('Hill Descent Assist', 'hill-descent-assist', NULL, 1, NOW(), NOW()),
    ('Hill start Assist', 'hill-start-assist', NULL, 1, NOW(), NOW()),
    ('Push button start', 'push-button-start', NULL, 1, NOW(), NOW()),
    ('Back - up warning', 'back-up-warning', NULL, 1, NOW(), NOW()),
    ('Automatic parallel parking', 'automatic-parallel-parking', NULL, 1, NOW(), NOW()),
    ('Parking Sensors', 'parking-sensors', NULL, 1, NOW(), NOW()),
    ('Side view camera', 'side-view-camera', NULL, 1, NOW(), NOW()),
    ('Blind spot warning', 'blind-spot-warning', NULL, 1, NOW(), NOW()),
    ('Lane Departure warning', 'lane-departure-warning', NULL, 1, NOW(), NOW()),
    ('Drowsiness Alert', 'drowsiness-alert', NULL, 1, NOW(), NOW()),
    ('Lane keeping', 'lane-keeping', NULL, 1, NOW(), NOW()),
    ('Anti-lock Braking System', 'anti-lock-braking-system', NULL, 1, NOW(), NOW()),
    ('Air Condition', 'air-condition', NULL, 1, NOW(), NOW()),
    ('PS', 'ps', NULL, 1, NOW(), NOW()),
    ('Power Windows', 'power-windows', NULL, 1, NOW(), NOW()),
    ('Airbag', 'airbag', NULL, 1, NOW(), NOW()),
    ('Multifunction Steering', 'multifunction-steering', NULL, 1, NOW(), NOW()),
    ('Navigation', 'navigation', NULL, 1, NOW(), NOW()),
    ('LED Headlights', 'led-headlights', NULL, 1, NOW(), NOW()),
    ('360'' Camera', '360-camera', NULL, 1, NOW(), NOW()),
    ('Modellistar Bodykit', 'modellistar-bodykit', NULL, 1, NOW(), NOW()),
    ('TV', 'tv', NULL, 1, NOW(), NOW()),
    ('Fog Light', 'fog-light', NULL, 1, NOW(), NOW()),
    ('Reverse Camera', 'reverse-camera', NULL, 1, NOW(), NOW()),
    ('Alloy Wheel', 'alloy-wheel', NULL, 1, NOW(), NOW()),
    ('Dual AC', 'dual-ac', NULL, 1, NOW(), NOW()),
    ('Leather Seats', 'leather-seats', NULL, 1, NOW(), NOW()),
    ('ETC', 'etc', NULL, 1, NOW(), NOW()),
    ('All kind of working Medical Instruments', 'all-kind-of-working-medical-instruments', NULL, 1, NOW(), NOW()),
    ('AW', 'aw', NULL, 1, NOW(), NOW()),
    ('Dual Moon Roof', 'dual-moon-roof', NULL, 1, NOW(), NOW()),
    ('Dual Power Door', 'dual-power-door', NULL, 1, NOW(), NOW()),
    ('Power Boot Door', 'power-boot-door', NULL, 1, NOW(), NOW()),
    ('Power Seats', 'power-seats', NULL, 1, NOW(), NOW()),
    ('Digital Inner Mirror', 'digital-inner-mirror', NULL, 1, NOW(), NOW()),
    ('Safety Sense', 'safety-sense', NULL, 1, NOW(), NOW()),
    ('Electric Power Assisted Steering', 'electric-power-assisted-steering', NULL, 1, NOW(), NOW()),
    ('Cornering Brake Control', 'cornering-brake-control', NULL, 1, NOW(), NOW()),
    ('Adaptive Dynamics', 'adaptive-dynamics', NULL, 1, NOW(), NOW()),
    ('Twin-speed transfer box (high/low range)', 'twin-speed-transfer-box-highlow-range', NULL, 1, NOW(), NOW()),
    ('Electronic Air Suspension', 'electronic-air-suspension', NULL, 1, NOW(), NOW()),
    ('8-speed Automatic Transmission', '8-speed-automatic-transmission', NULL, 1, NOW(), NOW()),
    ('Dynamic Stability Control (DSC)', 'dynamic-stability-control-dsc', NULL, 1, NOW(), NOW()),
    ('Roll Stability Control (RSC)', 'roll-stability-control-rsc', NULL, 1, NOW(), NOW()),
    ('Three-zone Climate Control with Rear Heating and Cooling Assist', 'three-zone-climate-control-with-rear-heating-and-cooling-assist', NULL, 1, NOW(), NOW()),
    ('Sunvisors with illuminated vanity mirrors', 'sunvisors-with-illuminated-vanity-mirrors', NULL, 1, NOW(), NOW()),
    ('Air Quality Sensor', 'air-quality-sensor', NULL, 1, NOW(), NOW()),
    ('Power operated child locks', 'power-operated-child-locks', NULL, 1, NOW(), NOW()),
    ('Android Auto™', 'android-auto', NULL, 1, NOW(), NOW()),
    ('Head-up Display', 'head-up-display', NULL, 1, NOW(), NOW()),
    ('Apple CarPlay', 'apple-carplay', NULL, 1, NOW(), NOW()),
    ('Smart Key', 'smart-key', NULL, 1, NOW(), NOW()),
    ('Floor Mats', 'floor-mats', NULL, 1, NOW(), NOW()),
    ('4 Zone Independent Air Conditioning', '4-zone-independent-air-conditioning', NULL, 1, NOW(), NOW()),
    ('Nano Air Purifier', 'nano-air-purifier', NULL, 1, NOW(), NOW()),
    ('12.3" High Resolution EMV Display', '123-high-resolution-emv-display', NULL, 1, NOW(), NOW()),
    ('4.2" TFT Multi Information Display', '42-tft-multi-information-display', NULL, 1, NOW(), NOW()),
    ('-9 Speakers', '9-speakers', NULL, 1, NOW(), NOW()),
    ('Automatic Rain Sensing Front Wipers', 'automatic-rain-sensing-front-wipers', NULL, 1, NOW(), NOW()),
    ('LED Daytime Running Lights', 'led-daytime-running-lights', NULL, 1, NOW(), NOW()),
    ('Extra Rear Leg Room for maximum comfort', 'extra-rear-leg-room-for-maximum-comfort', NULL, 1, NOW(), NOW()),
    ('German Nappa Leather with Diamond Design.', 'german-nappa-leather-with-diamond-design', NULL, 1, NOW(), NOW()),
    ('All 4 Electric seat with massage features with Multi comfort Adjustments.', 'all-4-electric-seat-with-massage-features-with-multi-comfort-adjustments', NULL, 1, NOW(), NOW()),
    ('Multi-Terrain Monitor', 'multi-terrain-monitor', NULL, 1, NOW(), NOW()),
    ('Dual Screen Rear-seat Entertainment System', 'dual-screen-rear-seat-entertainment-system', NULL, 1, NOW(), NOW()),
    ('12.3 Inch Split-Screen Multimedia Display.', '123-inch-split-screen-multimedia-display', NULL, 1, NOW(), NOW()),
    ('Color Head-up Display', 'color-head-up-display', NULL, 1, NOW(), NOW()),
    ('Panoramic View Monitor', 'panoramic-view-monitor', NULL, 1, NOW(), NOW()),
    ('Bluetooth', 'bluetooth', NULL, 1, NOW(), NOW()),
    ('USB', 'usb', NULL, 1, NOW(), NOW()),
    ('SiriusXM Satellite Radio', 'siriusxm-satellite-radio', NULL, 1, NOW(), NOW()),
    ('4 Zone Automatic Climate Control', '4-zone-automatic-climate-control', NULL, 1, NOW(), NOW()),
    ('Illuminated Console', 'illuminated-console', NULL, 1, NOW(), NOW()),
    ('Wood Trim', 'wood-trim', NULL, 1, NOW(), NOW()),
    ('120V AC power Outlet', '120v-ac-power-outlet', NULL, 1, NOW(), NOW()),
    ('Adaptive Variable Suspension', 'adaptive-variable-suspension', NULL, 1, NOW(), NOW()),
    ('Crawl Control', 'crawl-control', NULL, 1, NOW(), NOW()),
    ('Sport Grille and Front Spoilers', 'sport-grille-and-front-spoilers', NULL, 1, NOW(), NOW()),
    ('Sport Rear valance', 'sport-rear-valance', NULL, 1, NOW(), NOW()),
    ('21 inch Forged machined-finish alloy wheels', '21-inch-forged-machined-finish-alloy-wheels', NULL, 1, NOW(), NOW()),
    ('Sport rear valance', 'sport-rear-valance-1', NULL, 1, NOW(), NOW()),
    ('Sport-design side mirrors with chrome detail', 'sport-design-side-mirrors-with-chrome-detail', NULL, 1, NOW(), NOW()),
    ('Fixed Key Ignition', 'fixed-key-ignition', NULL, 1, NOW(), NOW()),
    ('Camouflage Canopy', 'camouflage-canopy', NULL, 1, NOW(), NOW()),
    ('Pintle Hitch In Tool Box', 'pintle-hitch-in-tool-box', NULL, 1, NOW(), NOW()),
    ('Jerry Can Holders', 'jerry-can-holders', NULL, 1, NOW(), NOW()),
    ('Tool Box', 'tool-box', NULL, 1, NOW(), NOW()),
    ('Air Vents', 'air-vents', NULL, 1, NOW(), NOW()),
    ('Glove Box', 'glove-box', NULL, 1, NOW(), NOW()),
    ('Wind Up Windows', 'wind-up-windows', NULL, 1, NOW(), NOW()),
    ('8 x Forward Gears', '8-x-forward-gears', NULL, 1, NOW(), NOW()),
    ('8 x Reverse Gears', '8-x-reverse-gears', NULL, 1, NOW(), NOW()),
    ('Roof Hatch', 'roof-hatch', NULL, 1, NOW(), NOW()),
    ('Spare Wheel', 'spare-wheel', NULL, 1, NOW(), NOW()),
    ('Suspension Type Coil Over', 'suspension-type-coil-over', NULL, 1, NOW(), NOW()),
    ('BOSE Sound System', 'bose-sound-system', NULL, 1, NOW(), NOW()),
    ('Dual side rear Auto door', 'dual-side-rear-auto-door', NULL, 1, NOW(), NOW()),
    ('Paddle Shifter', 'paddle-shifter', NULL, 1, NOW(), NOW()),
    ('Drive camera recorder', 'drive-camera-recorder', NULL, 1, NOW(), NOW()),
    ('Turbocharger', 'turbocharger', NULL, 1, NOW(), NOW()),
    ('Idling Stop', 'idling-stop', NULL, 1, NOW(), NOW()),
    ('Anti-theft Device', 'anti-theft-device', NULL, 1, NOW(), NOW()),
    ('Electric Retractable Mirror', 'electric-retractable-mirror', NULL, 1, NOW(), NOW()),
    ('Power Seats', 'power-seats-1', NULL, 1, NOW(), NOW()),
    ('DVD Playback', 'dvd-playback', NULL, 1, NOW(), NOW()),
    ('Seat Heater', 'seat-heater', NULL, 1, NOW(), NOW()),
    ('Collision Safety Body', 'collision-safety-body', NULL, 1, NOW(), NOW()),
    ('Collision Damage Reduction System', 'collision-damage-reduction-system', NULL, 1, NOW(), NOW()),
    ('Clearance Sonar', 'clearance-sonar', NULL, 1, NOW(), NOW()),
    ('Auto Light', 'auto-light', NULL, 1, NOW(), NOW()),
    ('Smart Key', 'smart-key-1', NULL, 1, NOW(), NOW()),
    ('Run Flat Tire', 'run-flat-tire', NULL, 1, NOW(), NOW());
